/*
 * DrawArea.java
 *
 * Created on 13 de Maio de 2005, 9:18
 */

/**
 *
 * @author  ei04116
 */
import java.awt.Dimension;
import javax.swing.*;
import G4_InterfClasses.*;
public class DrawArea extends javax.swing.JInternalFrame {

    static final int desktopWidth = 500;

    static final int desktopHeight = 400;

    static final int desktopMargin = 10;

    static int contador=0;

    DrawProg drawProg;

    MyCanvas   myCanvas;

    

    /** Creates new form DrawArea */

    public DrawArea(DrawProg source) {
        setTitle("Draw Area "+(++contador));
        initComponents();

       

        drawProg = source;

        setDrawAreaSize();

    

        pack();

        

        myCanvas = new MyCanvas(this);

        getContentPane().add(myCanvas);

        

  }

  

  public int getMargin()

  {

    return(desktopMargin);

  }

  

  private void setDrawAreaSize()

  {

    setPreferredSize(new Dimension(desktopWidth, desktopHeight));

    setSize(new Dimension(desktopWidth, desktopHeight));

    setLocation(desktopMargin, desktopMargin);

  }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
  
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        pack();
    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
  

