/*
 * DrawProg.java
 *
 * Created on 13 de Maio de 2005, 8:53
 */

/**
 *
 * @author  ei04116
 */
import java.awt.Dimension;
import javax.swing.*;
import G4_InterfClasses.*;
public class DrawProg extends javax.swing.JFrame {
   

    DrawArea drawArea;
 

    /** Creates new form DrawProg */

    public DrawProg() {
    setTitle("Draw Program");
    initComponents();
    tools[LINETOOL] = new LineTool();
    tools[RECTTOOL] = new RectTool();
    tools[POLYTOOL] = new PolyTool();
 
    toolSelected = tools[LINETOOL];
    toolSelected.startTool();
      

        //Set up the GUI.

        drawArea = createDrawArea();

        jDesktopPane1.add(drawArea);

        jDesktopPane1.setPreferredSize(new Dimension(drawArea.getWidth() + 2 * drawArea.getMargin(), drawArea.getHeight() + 2 * drawArea.getMargin()));

    

        pack();

    }


    

  private DrawArea createDrawArea()

  {

    DrawArea dArea = new DrawArea(this);

    dArea.setVisible(true); 

    try {

      dArea.setSelected(true);

    } catch (Exception e) { };
   

    return(dArea);

  } 

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jTextFieldl = new javax.swing.JPanel();
        Variáveis = new javax.swing.JLabel();
        RectButton = new javax.swing.JButton();
        LineBotao = new javax.swing.JButton();
        PolyButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        ChangeColorButton = new javax.swing.JButton();
        ChangeColorTool = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        jTextFieldl.setLayout(new java.awt.GridBagLayout());

        jTextFieldl.setPreferredSize(new java.awt.Dimension(120, 100));
        Variáveis.setText("X,Y:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jTextFieldl.add(Variáveis, gridBagConstraints);

        RectButton.setBackground(new java.awt.Color(255, 255, 153));
        RectButton.setText("Rect");
        RectButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Botao2(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jTextFieldl.add(RectButton, gridBagConstraints);

        LineBotao.setBackground(new java.awt.Color(102, 255, 0));
        LineBotao.setIcon(new javax.swing.ImageIcon("F:\\line.gif"));
        LineBotao.setText("Line");
        LineBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LineBotaoActionPerformed(evt);
            }
        });
        LineBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LineBotaoMouseClicked(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jTextFieldl.add(LineBotao, gridBagConstraints);

        PolyButton.setBackground(new java.awt.Color(0, 204, 204));
        PolyButton.setText("Poly");
        PolyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Botao3(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jTextFieldl.add(PolyButton, gridBagConstraints);

        ClearButton.setBackground(new java.awt.Color(0, 0, 204));
        ClearButton.setText("ClearDraw");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });
        ClearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearButton(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jTextFieldl.add(ClearButton, gridBagConstraints);

        ChangeColorButton.setBackground(new java.awt.Color(153, 153, 0));
        ChangeColorButton.setText("ChangeColor");
        ChangeColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeColorButtonActionPerformed(evt);
            }
        });
        ChangeColorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeColor(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jTextFieldl.add(ChangeColorButton, gridBagConstraints);

        ChangeColorTool.setBackground(new java.awt.Color(0, 153, 153));
        ChangeColorTool.setText("ChangeColorTool");
        ChangeColorTool.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangeColoTool(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 9;
        jTextFieldl.add(ChangeColorTool, gridBagConstraints);

        jTextField1.setText("jTextF0.1.ield1");
        jTextField1.setPreferredSize(new java.awt.Dimension(55, 23));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jTextField1MouseDragged(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        jTextFieldl.add(jTextField1, gridBagConstraints);

        getContentPane().add(jTextFieldl, java.awt.BorderLayout.EAST);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void jTextField1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseDragged
    // TODO add your handling code here:
        setTexto(evt.getX(),evt.getY());
    }//GEN-LAST:event_jTextField1MouseDragged

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void ChangeColoTool(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangeColoTool
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangeColoTool

    private void ChangeColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeColorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangeColorButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void changeColor(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeColor
        // TODO add your handling code here:
        toolSelected.changeColor();
    }//GEN-LAST:event_changeColor

    private void ClearButton(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearButton
        // TODO add your handling code here:
        toolSelected.stopTool();
        jDesktopPane1.removeAll();
        drawArea=createDrawArea();
        jDesktopPane1.add(drawArea);

        jDesktopPane1.setPreferredSize(new Dimension(drawArea.getWidth() + 2 * drawArea.getMargin(), drawArea.getHeight() + 2 * drawArea.getMargin()));

        pack();
    }//GEN-LAST:event_ClearButton

    private void Botao3(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Botao3
        // TODO add your handling code here:
        toolSelected.stopTool();
        changeTool(POLYTOOL);
    }//GEN-LAST:event_Botao3

    private void Botao2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Botao2
        // TODO add your handling code here:
        toolSelected.stopTool();
        changeTool(RECTTOOL);
        
    }//GEN-LAST:event_Botao2

    private void LineBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LineBotaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LineBotaoActionPerformed

    private void LineBotaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LineBotaoMouseClicked
        // TODO add your handling code here:
        toolSelected.stopTool();
        changeTool(LINETOOL);
    }//GEN-LAST:event_LineBotaoMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DrawProg().setVisible(true);
            }
        });
    }
    public void setTexto(int x, int y) {
        jTextField1.setText(x+" , "+y);
    }
  static final int LINETOOL = 0;
  static final int RECTTOOL = 1;
  static final int POLYTOOL = 2;
       // variáveis locais a DrawProg
  private AnyTool toolSelected;
  private AnyTool[] tools = new AnyTool[3];
 

  public void changeTool(int newTool)
  {
    toolSelected.stopTool();
    toolSelected = tools[newTool];
    toolSelected.startTool();
  }
  
  public AnyTool getToolSelected()
  {
    return(toolSelected);
  }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChangeColorButton;
    private javax.swing.JButton ChangeColorTool;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton LineBotao;
    private javax.swing.JButton PolyButton;
    private javax.swing.JButton RectButton;
    private javax.swing.JLabel Variáveis;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel jTextFieldl;
    // End of variables declaration//GEN-END:variables
    
}
